[package]
name = "tasklings"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "6.0.0"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.5"
crossterm = "0.29.0"
chrono = { version = "0.4", features = ["serde"] }
ratatui = "0.29.0"

